//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Ocs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Webinar_VideoL
    {
        public int Id { get; set; }
        public double XId { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public string Iconimg { get; set; }
        public string Iconimg2 { get; set; }
        public string language { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Webinar_VideoXL Webinar_VideoXL { get; set; }
    }
}
