//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH_Ocs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Webinar_LikeV
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public double VideoXId { get; set; }
    
        public virtual Webinar_VideoXL Webinar_VideoXL { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
